
name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 5
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        run: dotnet dotnet workload restore --project Laerdal.Dfu.Bindings.iOS/Laerdal.Dfu.Bindings.iOS.csproj
        shell: bash
        
      - name: Build
        run: dotnet build -p:GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
        shell: bash
        env: 
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: Output