
name: Builder

env:
  Build_Repository_LocalPath: ${{ github.workspace }}
  Laerdal_Test_Results_Folderpath: '$Build_Repository_LocalPath/TestResults'
  
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: macos-14

    steps:

      - uses: actions/checkout@v3
      
      
      - run: dotnet dotnet workload restore --project Laerdal.Dfu.Bindings.iOS/Laerdal.Dfu.Bindings.iOS.csproj
        shell: bash
        
      - run: dotnet build 
        shell: bash
        env: 
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Output Artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: Output
 
