
name: Builder

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: macos-14

    steps:

      - uses: actions/checkout@v3
      
      
      - run: dotnet dotnet workload restore --project Laerdal.Dfu.Bindings.iOS/Laerdal.Dfu.Bindings.iOS.csproj
        shell: bash
        
      - run: dotnet build -p:GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
        shell: bash
        env: 
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Output Artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: Output
 
